import Head from 'next/head';
import Image from 'next/image';
import React from 'react';

import { useRouter } from 'next/router';
import styles from './../../../styles/Default.module.css';
import { RouteGuard } from './RouteGuard';

import Nav from 'react-bootstrap/Nav';
import Link from 'next/link';
import { ACCESS_TOKEN_KEY } from '../../constants/storage';

type Props = {
  title: string;
  children: React.ReactNode;
  isGuestRoute?: boolean;
};

export const PageLayout: React.FC<Props> = ({
  title,
  children,
  isGuestRoute,
}) => {
  const router = useRouter();

  const handleLogout = () => {
    if (typeof localStorage === 'undefined') {
      return;
    }

    console.log('should handle login');

    localStorage.removeItem(ACCESS_TOKEN_KEY);

    router.push('/');
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <div className='page-content '>
            {isGuestRoute ? (
              <>{children}</>
            ) : (
              <>
                <RouteGuard>{children}</RouteGuard>

                {/* <div className='my-5'>
                <a href='#' className='btn btn-danger' onClick={handleLogout}>
                  Logout
                </a>
              </div> */}
              </>
            )}
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            target='_blank'
            rel='noopener noreferrer'
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src='/vercel.svg'
                alt='Vercel Logo'
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};
